[server]
address = "localhost"
port = 8505
runOnSave = true
[browser]
gatherUsageStats = false
[client]
toolbarMode = "minimal" #top right streamlit toolbar.
[runner]
magicEnabled = false
[theme]
base="light"
